// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (c) 2026 
 * Author: Burst_Caster <swer15l23@gmail.com>
 */
 
#ifndef __PINCTRL_MTK_MT6582_H
#define __PINCTRL_MTK_MT6582_H

#include "pinctrl-paris.h"


static const struct mtk_pin_desc mtk_pins_mt6582[] = {
	MTK_PIN(
 	 	0, "EINT0",
		MTK_EINT_FUNCTION(0, 0),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO0"),
		MTK_FUNCTION(1, "PWM1"),
		MTK_FUNCTION(2, "DPI_D4"),
		MTK_FUNCTION(5, "CONN_DSP_JDO"),
		MTK_FUNCTION(6, "DSPJTD")
	),
	MTK_PIN(
 	 	1, "EINT1",
		MTK_EINT_FUNCTION(0, 1),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO1"),
		MTK_FUNCTION(1, "PWM2"),
		MTK_FUNCTION(2, "DPI_D5"),
		MTK_FUNCTION(3, "MD_EINT1"),
		MTK_FUNCTION(4, "TDD_TDO"),
		MTK_FUNCTION(5, "CONN_MCU_TDO")
	),
	MTK_PIN(
 	 	2, "EINT2",
		MTK_EINT_FUNCTION(0, 2),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO2"),
		MTK_FUNCTION(1, "CLKM0"),
		MTK_FUNCTION(2, "DPI_D6"),
		MTK_FUNCTION(3, "MD_EINT2"),
		MTK_FUNCTION(5, "CONN_MCU_DBGACK_N"),
		MTK_FUNCTION(6, "KCOL4")
	),
	MTK_PIN(
 	 	3, "EINT3",
		MTK_EINT_FUNCTION(0, 3),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO3"),
		MTK_FUNCTION(1, "CLKM1"),
		MTK_FUNCTION(2, "DPI_D7"),
		MTK_FUNCTION(3, "SPI_MI"),
		MTK_FUNCTION(4, "MD_EINT3"),
		MTK_FUNCTION(5, "CONN_MCU_DBGI_N"),
		MTK_FUNCTION(6, "KCOL5")
	),
	MTK_PIN(
 	 	4, "EINT4",
		MTK_EINT_FUNCTION(0, 4),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO4"),
		MTK_FUNCTION(1, "CLKM2"),
		MTK_FUNCTION(2, "DPI_D8"),
		MTK_FUNCTION(3, "SPI_MO"),
		MTK_FUNCTION(4, "TDD_TCK"),
		MTK_FUNCTION(5, "CONN_MCU_TCK0"),
		MTK_FUNCTION(6, "CONN_MCU_AICE_JCKC")
	),
	MTK_PIN(
 	 	5, "EINT5",
		MTK_EINT_FUNCTION(0, 5),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO5"),
		MTK_FUNCTION(1, "UCTS2"),
		MTK_FUNCTION(2, "DPI_D9"),
		MTK_FUNCTION(3, "SPI_CS"),
		MTK_FUNCTION(4, "TDD_TDI"),
		MTK_FUNCTION(5, "CONN_MCU_TDI"),
		MTK_FUNCTION(6, "KCOL6")
	),
	MTK_PIN(
 	 	6, "EINT6",
		MTK_EINT_FUNCTION(0, 6),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO6"),
		MTK_FUNCTION(1, "URTS2"),
		MTK_FUNCTION(2, "DPI_D10"),
		MTK_FUNCTION(3, "SPI_CK"),
		MTK_FUNCTION(4, "TDD_TRSTN"),
		MTK_FUNCTION(5, "CONN_MCU_TRST_B"),
		MTK_FUNCTION(6, "KCOL7")
	),
	MTK_PIN(
 	 	7, "EINT7",
		MTK_EINT_FUNCTION(0, 7),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO7"),
		MTK_FUNCTION(1, "UCTS3"),
		MTK_FUNCTION(2, "DPI_D11"),
		MTK_FUNCTION(3, "SDA1"),
		MTK_FUNCTION(4, "TDD_TMS"),
		MTK_FUNCTION(5, "CONN_MCU_TMS"),
		MTK_FUNCTION(6, "CONN_MCU_AICE_JMSC")
	),
	MTK_PIN(
 	 	8, "EINT8",
		MTK_EINT_FUNCTION(0, 8),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO8"),
		MTK_FUNCTION(1, "URTS3"),
		MTK_FUNCTION(2, "CLKM3"),
		MTK_FUNCTION(3, "SCL1"),
		MTK_FUNCTION(4, "NLD9"),
		MTK_FUNCTION(6, "MD_EINT1")
	),
	MTK_PIN(
 	 	9, "EINT9",
		MTK_EINT_FUNCTION(0, 9),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO9"),
		MTK_FUNCTION(2, "SDA2"),
		MTK_FUNCTION(3, "EXT_FRAME_SYNC"),
		MTK_FUNCTION(4, "NWEB"),
		MTK_FUNCTION(5, "MD_EINT2")
	),
	MTK_PIN(
 	 	10, "EINT10",
		MTK_EINT_FUNCTION(0, 10),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO10"),
		MTK_FUNCTION(2, "SCL2"),
		MTK_FUNCTION(3, "EXT_FRAME_SYNC"),
		MTK_FUNCTION(4, "NCEB0"),
		MTK_FUNCTION(5, "MD_EINT3")
	),
	MTK_PIN(
 	 	11, "EINT11",
		MTK_EINT_FUNCTION(0, 11),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO11"),
		MTK_FUNCTION(2, "PWM2"),
		MTK_FUNCTION(3, "KROW3"),
		MTK_FUNCTION(4, "NLD12")
	),
	MTK_PIN(
 	 	12, "GPIO12",
		MTK_EINT_FUNCTION(0, 12),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO12"),
		MTK_FUNCTION(2, "PWM0"),
		MTK_FUNCTION(3, "KCOL3"),
		MTK_FUNCTION(4, "NLD13"),
		MTK_FUNCTION(7, "DBG_MON_B_6")
	),
	MTK_PIN(
 	 	13, "GPIO13",
		MTK_EINT_FUNCTION(0, 13),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO13"),
		MTK_FUNCTION(2, "GPS_FRAME_SYNC"),
		MTK_FUNCTION(4, "MD_EINT1"),
		MTK_FUNCTION(7, "DBG_MON_B_7")
	),
	MTK_PIN(
 	 	14, "EINT14",
		MTK_EINT_FUNCTION(0, 14),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO14"),
		MTK_FUNCTION(2, "DAC_SAT_OUT"),
		MTK_FUNCTION(3, "ANT_SEL3"),
		MTK_FUNCTION(4, "MD_EINT2"),
		MTK_FUNCTION(5, "CONN_MCU_DBGACK_N"),
		MTK_FUNCTION(7, "DBG_MON_B_8")
	),
	MTK_PIN(
 	 	15, "EINT15",
		MTK_EINT_FUNCTION(0, 15),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO15"),
		MTK_FUNCTION(2, "DAC_WS"),
		MTK_FUNCTION(3, "ANT_SEL4"),
		MTK_FUNCTION(4, "MD_EINT3"),
		MTK_FUNCTION(5, "CONN_MCU_DBGI_N"),
		MTK_FUNCTION(7, "DBG_MON_B_9")
	),
	MTK_PIN(
 	 	16, "EINT16",
		MTK_EINT_FUNCTION(0, 16),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO16"),
		MTK_FUNCTION(2, "DAC_CK"),
		MTK_FUNCTION(3, "ANT_SEL5"),
		MTK_FUNCTION(4, "NLD15"),
		MTK_FUNCTION(5, "CONN_MCU_TRST_B"),
		MTK_FUNCTION(7, "DBG_MON_B_10")
	),
	MTK_PIN(
 	 	17, "EINT17",
		MTK_EINT_FUNCTION(0, 17),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO17"),
		MTK_FUNCTION(1, "UCTS0"),
		MTK_FUNCTION(2, "BSI_B_CLK"),
		MTK_FUNCTION(3, "CLKM0"),
		MTK_FUNCTION(4, "IDDIG"),
		MTK_FUNCTION(7, "DBG_MON_B_11")
	),
	MTK_PIN(
 	 	18, "EINT18",
		MTK_EINT_FUNCTION(0, 18),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO18"),
		MTK_FUNCTION(1, "URTS0"),
		MTK_FUNCTION(2, "BSI_B_DATA0"),
		MTK_FUNCTION(3, "I2SOUT_LRCK"),
		MTK_FUNCTION(4, "DRV_VBUS"),
		MTK_FUNCTION(7, "DBG_MON_B_12")
	),
	MTK_PIN(
 	 	19, "EINT19",
		MTK_EINT_FUNCTION(0, 19),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO19"),
		MTK_FUNCTION(1, "UCTS1"),
		MTK_FUNCTION(2, "BSI_B_EN"),
		MTK_FUNCTION(3, "I2SOUT_BCK"),
		MTK_FUNCTION(4, "CLKM1"),
		MTK_FUNCTION(7, "DBG_MON_B_13")
	),
	MTK_PIN(
 	 	20, "EINT20",
		MTK_EINT_FUNCTION(0, 20),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO20"),
		MTK_FUNCTION(1, "URTS1"),
		MTK_FUNCTION(2, "PCM_TX"),
		MTK_FUNCTION(3, "I2SOUT_DATA_OUT"),
		MTK_FUNCTION(4, "CLKM2"),
		MTK_FUNCTION(7, "DBG_MON_B_14")
	),
	MTK_PIN(
 	 	21, "PWRAP_SPI0_MI",
		MTK_EINT_FUNCTION(0, 21),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO21"),
		MTK_FUNCTION(1, "PWRAP_SPIDO"),
		MTK_FUNCTION(2, "PWRAP_SPIDI")
	),
	MTK_PIN(
 	 	22, "PWRAP_SPI0_MO",
		MTK_EINT_FUNCTION(0, 22),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO22"),
		MTK_FUNCTION(1, "PWRAP_SPIDI"),
		MTK_FUNCTION(2, "PWRAP_SPIDO")
	),
	MTK_PIN(
 	 	23, "PWRAP_SPI0_CK",
		MTK_EINT_FUNCTION(0, 23),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO23"),
		MTK_FUNCTION(1, "PWRAP_SPICK_I")
	),
	MTK_PIN(
 	 	24, "PWRAP_SPI0_CSN",
		MTK_EINT_FUNCTION(0, 24),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO24"),
		MTK_FUNCTION(1, "PWRAP_SPICS_B_I")
	),
	MTK_PIN(
 	 	25, "PWRAP_INT",
		MTK_EINT_FUNCTION(0, 25),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO25")
	),
	MTK_PIN(
 	 	26, "AUD_CLK_MOSI",
		MTK_EINT_FUNCTION(0, 26),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO26"),
		MTK_FUNCTION(1, "AUD_CLK"),
		MTK_FUNCTION(2, "ADC_CK")
	),
	MTK_PIN(
 	 	27, "AUD_DAT_MISO",
		MTK_EINT_FUNCTION(0, 27),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO27"),
		MTK_FUNCTION(1, "AUD_MISO"),
		MTK_FUNCTION(2, "ADC_DAT_IN"),
		MTK_FUNCTION(3, "AUD_MOSI")
	),
	MTK_PIN(
 	 	28, "AUD_DAT_MOSI",
		MTK_EINT_FUNCTION(0, 28),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO28"),
		MTK_FUNCTION(1, "AUD_MOSI"),
		MTK_FUNCTION(2, "ADC_WS"),
		MTK_FUNCTION(3, "AUD_MISO")
	),
	MTK_PIN(
 	 	29, "SIM1_SCLK",
		MTK_EINT_FUNCTION(0, 29),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO29"),
		MTK_FUNCTION(1, "MD1_SIM1_SCLK"),
		MTK_FUNCTION(2, "MD1_SIM2_SCLK")
	),
	MTK_PIN(
 	 	30, "SIM1_SRST",
		MTK_EINT_FUNCTION(0, 30),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO30"),
		MTK_FUNCTION(1, "MD1_SIM1_SRST"),
		MTK_FUNCTION(2, "MD1_SIM2_SRST"),
		MTK_FUNCTION(3, "PWM3")
	),
	MTK_PIN(
 	 	31, "SIM1_SIO",
		MTK_EINT_FUNCTION(0, 31),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO31"),
		MTK_FUNCTION(1, "MD1_SIM1_SDAT"),
		MTK_FUNCTION(2, "MD1_SIM2_SDAT")
	),
	MTK_PIN(
 	 	32, "SIM2_SCLK",
		MTK_EINT_FUNCTION(0, 32),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO32"),
		MTK_FUNCTION(1, "MD1_SIM2_SCLK"),
		MTK_FUNCTION(2, "MD1_SIM1_SCLK")
	),
	MTK_PIN(
 	 	33, "SIM2_SRST",
		MTK_EINT_FUNCTION(0, 33),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO33"),
		MTK_FUNCTION(1, "MD1_SIM2_SRST"),
		MTK_FUNCTION(2, "MD1_SIM1_SRST"),
		MTK_FUNCTION(3, "PWM4")
	),
	MTK_PIN(
 	 	34, "SIM2_SIO",
		MTK_EINT_FUNCTION(0, 34),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO34"),
		MTK_FUNCTION(1, "MD1_SIM2_SDAT"),
		MTK_FUNCTION(3, "MD1_SIM1_SDAT"),
		MTK_FUNCTION(7, "DBG_MON_B_0")
	),
	MTK_PIN(
 	 	35, "RTC32K_CK",
		MTK_EINT_FUNCTION(0, 35),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO35"),
		MTK_FUNCTION(1, "RTC32K_CK")
	),
	MTK_PIN(
 	 	36, "WATCHDOG",
		MTK_EINT_FUNCTION(0, 36),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO36"),
		MTK_FUNCTION(1, "WATCHDOG")
	),
	MTK_PIN(
 	 	37, "SRCLKENA",
		MTK_EINT_FUNCTION(0, 37),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO37"),
		MTK_FUNCTION(1, "SRCLKENA")
	),
	MTK_PIN(
 	 	38, "SRCLKENAI",
		MTK_EINT_FUNCTION(0, 38),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO38"),
		MTK_FUNCTION(1, "SRCLKENAI")
	),
	MTK_PIN(
 	 	39, "URXD2",
		MTK_EINT_FUNCTION(0, 39),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO39"),
		MTK_FUNCTION(1, "URXD2"),
		MTK_FUNCTION(2, "DPI_HSYNC"),
		MTK_FUNCTION(3, "UTXD2"),
		MTK_FUNCTION(4, "MD_URXD"),
		MTK_FUNCTION(6, "KROW4")
	),
	MTK_PIN(
 	 	40, "UTXD2",
		MTK_EINT_FUNCTION(0, 40),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO40"),
		MTK_FUNCTION(1, "UTXD2"),
		MTK_FUNCTION(2, "DPI_VSYNC"),
		MTK_FUNCTION(3, "URXD2"),
		MTK_FUNCTION(4, "MD_UTXD"),
		MTK_FUNCTION(5, "TDD_TXD"),
		MTK_FUNCTION(6, "KROW5")
	),
	MTK_PIN(
 	 	41, "URXD3",
		MTK_EINT_FUNCTION(0, 41),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO41"),
		MTK_FUNCTION(1, "URXD3"),
		MTK_FUNCTION(2, "DPI_CK"),
		MTK_FUNCTION(3, "UTXD3"),
		MTK_FUNCTION(4, "UCTS2"),
		MTK_FUNCTION(5, "PWM3"),
		MTK_FUNCTION(6, "KROW6")
	),
	MTK_PIN(
 	 	42, "UTXD3",
		MTK_EINT_FUNCTION(0, 42),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO42"),
		MTK_FUNCTION(1, "UTXD3"),
		MTK_FUNCTION(2, "DPI_DE"),
		MTK_FUNCTION(3, "URXD3"),
		MTK_FUNCTION(4, "URTS2"),
		MTK_FUNCTION(5, "PWM4"),
		MTK_FUNCTION(6, "KROW7")
	),
	MTK_PIN(
 	 	43, "PCM_CLK",
		MTK_EINT_FUNCTION(0, 43),
		DRV_GRP0,
		MTK_FUNCTION(0, "PCM_CLK0"),
		MTK_FUNCTION(1, "I2SIN1_BCK0"),
		MTK_FUNCTION(2, "I2SOUT_BCK"),
		MTK_FUNCTION(3, "CONN_DSP_JCK"),
		MTK_FUNCTION(4, "DSPJTCK")
	),
	MTK_PIN(
 	 	44, "PCM_SYNC",
		MTK_EINT_FUNCTION(0, 44),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO44"),
		MTK_FUNCTION(1, "PCM_SYNC"),
		MTK_FUNCTION(2, "DPI_D1"),
		MTK_FUNCTION(3, "I2SIN1_LRCK"),
		MTK_FUNCTION(4, "I2SOUT_LRCK"),
		MTK_FUNCTION(5, "CONN_DSP_JINTP"),
		MTK_FUNCTION(7, "DBG_MON_B_3")
	),
	MTK_PIN(
 	 	45, "PCM_RX",
		MTK_EINT_FUNCTION(0, 45),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO45"),
		MTK_FUNCTION(1, "PCM_RX"),
		MTK_FUNCTION(2, "DPI_D2"),
		MTK_FUNCTION(3, "I2SIN1_DATA_IN"),
		MTK_FUNCTION(4, "PCM_TX"),
		MTK_FUNCTION(5, "CONN_DSP_JDI"),
		MTK_FUNCTION(7, "DBG_MON_B_4")
	),
	MTK_PIN(
 	 	46, "PCM_TX",
		MTK_EINT_FUNCTION(0, 46),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO46"),
		MTK_FUNCTION(1, "PCM_TX"),
		MTK_FUNCTION(2, "DPI_D3"),
		MTK_FUNCTION(3, "I2SOUT_DATA_OUT"),
		MTK_FUNCTION(4, "PCM_RX"),
		MTK_FUNCTION(5, "CONN_DSP_JMS"),
		MTK_FUNCTION(6, "DSPJTMS"),
		MTK_FUNCTION(7, "DBG_MON_B_5")
	),
	MTK_PIN(
 	 	47, "ANT_SEL0",
		MTK_EINT_FUNCTION(0, 47),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO47"),
		MTK_FUNCTION(1, "ANT_SEL0"),
		MTK_FUNCTION(2, "PWM0"),
		MTK_FUNCTION(3, "CONN_MCU_DBGACK_N"),
		MTK_FUNCTION(7, "DBG_MON_A_0")
	),
	MTK_PIN(
 	 	48, "ANT_SEL1",
		MTK_EINT_FUNCTION(0, 48),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO48"),
		MTK_FUNCTION(1, "ANT_SEL1"),
		MTK_FUNCTION(2, "PWM1"),
		MTK_FUNCTION(3, "CONN_MCU_DBGI_N"),
		MTK_FUNCTION(7, "DBG_MON_A_1")
	),
	MTK_PIN(
 	 	49, "ANT_SEL2",
		MTK_EINT_FUNCTION(0, 49),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO49"),
		MTK_FUNCTION(1, "ANT_SEL2"),
		MTK_FUNCTION(2, "PWM2"),
		MTK_FUNCTION(3, "CONN_MCU_TRST_B"),
		MTK_FUNCTION(7, "DBG_MON_A_2")
	),
	MTK_PIN(
 	 	50, "BPI_BUS0",
		MTK_EINT_FUNCTION(0, 50),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO50"),
		MTK_FUNCTION(1, "BPI_BUS0"),
		MTK_FUNCTION(7, "DBG_MON_A_3")
	),
	MTK_PIN(
 	 	51, "BPI_BUS1",
		MTK_EINT_FUNCTION(0, 51),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO51"),
		MTK_FUNCTION(7, "DBG_MON_A_4")
	),
	MTK_PIN(
 	 	52, "BPI_BUS2",
		MTK_EINT_FUNCTION(0, 52),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO52"),
		MTK_FUNCTION(1, "BPI_BUS2"),
		MTK_FUNCTION(7, "DBG_MON_A_5")
	),
	MTK_PIN(
 	 	53, "BPI_BUS3",
		MTK_EINT_FUNCTION(0, 53),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO53"),
		MTK_FUNCTION(1, "BPI_BUS3"),
		MTK_FUNCTION(7, "DBG_MON_A_6")
	),
	MTK_PIN(
 	 	54, "BPI_BUS4",
		MTK_EINT_FUNCTION(0, 54),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO54"),
		MTK_FUNCTION(1, "BPI_BUS4"),
		MTK_FUNCTION(7, "DBG_MON_A_7")
	),
	MTK_PIN(
 	 	55, "BPI_BUS5",
		MTK_EINT_FUNCTION(0, 55),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO55"),
		MTK_FUNCTION(1, "BPI_BUS5"),
		MTK_FUNCTION(7, "DBG_MON_A_8")
	),
	MTK_PIN(
 	 	56, "BPI_BUS6",
		MTK_EINT_FUNCTION(0, 56),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO56"),
		MTK_FUNCTION(1, "BPI_BUS6"),
		MTK_FUNCTION(7, "DBG_MON_A_9")
	),
	MTK_PIN(
 	 	57, "BPI_BUS14",
		MTK_EINT_FUNCTION(0, 57),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO57"),
		MTK_FUNCTION(1, "BPI_BUS14"),
		MTK_FUNCTION(2, "CLKM1"),
		MTK_FUNCTION(7, "DBG_MON_A_10")
	),
	MTK_PIN(
 	 	58, "BPI_BUS15",
		MTK_EINT_FUNCTION(0, 58),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO58"),
		MTK_FUNCTION(1, "BPI_BUS15"),
		MTK_FUNCTION(7, "DBG_MON_A_11")
	),
	MTK_PIN(
 	 	59, "BPI_BUS7",
		MTK_EINT_FUNCTION(0, 59),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO59"),
		MTK_FUNCTION(1, "BPI_BUS7"),
		MTK_FUNCTION(7, "DBG_MON_A_12")
	),
	MTK_PIN(
 	 	60, "BPI_BUS8",
		MTK_EINT_FUNCTION(0, 60),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO60"),
		MTK_FUNCTION(1, "BPI_BUS8"),
		MTK_FUNCTION(7, "DBG_MON_A_13")
	),
	MTK_PIN(
 	 	61, "BPI_BUS9",
		MTK_EINT_FUNCTION(0, 61),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO61"),
		MTK_FUNCTION(1, "BPI_BUS9"),
		MTK_FUNCTION(7, "DBG_MON_A_14")
	),
	MTK_PIN(
 	 	62, "BPI_BUS10",
		MTK_EINT_FUNCTION(0, 63),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO62"),
		MTK_FUNCTION(1, "BPI_BUS10"),
		MTK_FUNCTION(7, "DBG_MON_A_15")
	),
	MTK_PIN(
 	 	63, "BPI_BUS11",
		MTK_EINT_FUNCTION(0, 63),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO63"),
		MTK_FUNCTION(1, "BPI_BUS11"),
		MTK_FUNCTION(7, "DBG_MON_A_16")
	),
	MTK_PIN(
 	 	64, "BPI_BUS12",
		MTK_EINT_FUNCTION(0, 64),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO64"),
		MTK_FUNCTION(1, "BPI_BUS12"),
		MTK_FUNCTION(2, "BSI_C_CLK"),
		MTK_FUNCTION(7, "DBG_MON_A_17")
	),
	MTK_PIN(
 	 	65, "BPI_BUS13",
		MTK_EINT_FUNCTION(0, 65),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO65"),
		MTK_FUNCTION(1, "BPI_BUS13"),
		MTK_FUNCTION(2, "BSI_C_DATA0"),
		MTK_FUNCTION(7, "DBG_MON_A_18")
	),
	MTK_PIN(
 	 	66, "BSI_EN",
		MTK_EINT_FUNCTION(0, 66),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO66"),
		MTK_FUNCTION(1, "BSI_A_EN"),
		MTK_FUNCTION(7, "DBG_MON_A_19")
	),
	MTK_PIN(
 	 	67, "BSI_CLK",
		MTK_EINT_FUNCTION(0, 67),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO67"),
		MTK_FUNCTION(1, "BSI_A_CLK"),
		MTK_FUNCTION(7, "DBG_MON_A_20")
	),
	MTK_PIN(
 	 	68, "BSI_DATA0",
		MTK_EINT_FUNCTION(0, 68),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO68"),
		MTK_FUNCTION(1, "BSI_A_DATA0"),
		MTK_FUNCTION(7, "DBG_MON_A_21")
	),
	MTK_PIN(
 	 	69, "BSI_DATA1",
		MTK_EINT_FUNCTION(0, 69),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO69"),
		MTK_FUNCTION(1, "BSI_A_DATA1"),
		MTK_FUNCTION(7, "DBG_MON_A_22")
	),
	MTK_PIN(
 	 	70, "BSI_DATA2",
		MTK_EINT_FUNCTION(0, 70),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO70"),
		MTK_FUNCTION(1, "BSI_A_DATA2"),
		MTK_FUNCTION(7, "DBG_MON_A_23")
	),
	MTK_PIN(
 	 	71, "TXBPI",
		MTK_EINT_FUNCTION(0, 71),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO71"),
		MTK_FUNCTION(1, "TXBPI"),
		MTK_FUNCTION(7, "DBG_MON_A_24")
	),
	MTK_PIN(
 	 	72, "VM0",
		MTK_EINT_FUNCTION(0, 72),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO72"),
		MTK_FUNCTION(1, "VM0"),
		MTK_FUNCTION(2, "CLKM3"),
		MTK_FUNCTION(7, "DBG_MON_A_25")
	),
	MTK_PIN(
 	 	73, "VM1",
		MTK_EINT_FUNCTION(0, 73),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO73"),
		MTK_FUNCTION(1, "VM1"),
		MTK_FUNCTION(2, "CLKM3"),
		MTK_FUNCTION(7, "DBG_MON_A_26")
	),
	MTK_PIN(
 	 	74, "KPROW0",
		MTK_EINT_FUNCTION(0, 74),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO74"),
		MTK_FUNCTION(1, "KPROW0")
	),
	MTK_PIN(
 	 	75, "KPCOL0",
		MTK_EINT_FUNCTION(0, 75),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO75"),
		MTK_FUNCTION(1, "KCOL0")
	),
	MTK_PIN(
 	 	76, "JTMS",
		MTK_EINT_FUNCTION(0, 76),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO76"),
		MTK_FUNCTION(1, "JTMS"),
		MTK_FUNCTION(2, "CONN_MCU_TMS")
	),
	MTK_PIN(
 	 	77, "JTCK",
		MTK_EINT_FUNCTION(0, 77),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO77"),
		MTK_FUNCTION(1, "JTCK"),
		MTK_FUNCTION(2, "CONN_MCU_TCK1")
	),
	MTK_PIN(
 	 	78, "JTDI",
		MTK_EINT_FUNCTION(0, 78),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO78"),
		MTK_FUNCTION(1, "JTDI"),
		MTK_FUNCTION(2, "CONN_MCU_TDI")
	),
	MTK_PIN(
 	 	79, "JTDO",
		MTK_EINT_FUNCTION(0, 79),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO79"),
		MTK_FUNCTION(1, "JTDO"),
		MTK_FUNCTION(2, "CONN_MCU_TDO")
	),
	MTK_PIN(
 	 	80, "SPI_CS",
		MTK_EINT_FUNCTION(0, 80),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO80"),
		MTK_FUNCTION(1, "SPI_CS"),
		MTK_FUNCTION(3, "I2SIN1_DATA_IN"),
		MTK_FUNCTION(7, "DBG_MON_B_15")
	),
	MTK_PIN(
 	 	81, "SPI_CK",
		MTK_EINT_FUNCTION(0, 81),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO81"),
		MTK_FUNCTION(1, "SPI_CK"),
		MTK_FUNCTION(3, "I2SIN1_LRCK"),
		MTK_FUNCTION(7, "DBG_MON_B_16")
	),
	MTK_PIN(
 	 	82, "SPI_MI",
		MTK_EINT_FUNCTION(0, 82),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO82"),
		MTK_FUNCTION(1, "SPI_MI"),
		MTK_FUNCTION(2, "SPI_MO"),
		MTK_FUNCTION(3, "I2SIN1_BCK1"),
		MTK_FUNCTION(7, "DBG_MON_B_17")
	),
	MTK_PIN(
 	 	83, "SPI_MO",
		MTK_EINT_FUNCTION(0, 83),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO83"),
		MTK_FUNCTION(1, "SPI_MO"),
		MTK_FUNCTION(2, "SPI_MI")
	),
	MTK_PIN(
 	 	84, "SDA0",
		MTK_EINT_FUNCTION(0, 84),
		DRV_GRP2,
		MTK_FUNCTION(1, "SDA0")
	),
	MTK_PIN(
 	 	85, "SCL0",
		MTK_EINT_FUNCTION(0, 85),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO85"),
		MTK_FUNCTION(1, "SCL0")
	),
	MTK_PIN(
 	 	86, "SDA1",
		MTK_EINT_FUNCTION(0, 86),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO86"),
		MTK_FUNCTION(1, "SDA1")
	),
	MTK_PIN(
 	 	87, "SCL1",
		MTK_EINT_FUNCTION(0, 87),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO87"),
		MTK_FUNCTION(1, "SCL1")
	),
	MTK_PIN(
 	 	88, "SDA2",
		MTK_EINT_FUNCTION(0, 88),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO88"),
		MTK_FUNCTION(1, "SDA2"),
		MTK_FUNCTION(2, "PWM1")
	),
	MTK_PIN(
 	 	89, "SCL2",
		MTK_EINT_FUNCTION(0, 89),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO89"),
		MTK_FUNCTION(1, "SCL2"),
		MTK_FUNCTION(2, "PWM2")
	),
	MTK_PIN(
 	 	90, "DISP_PWM",
		MTK_EINT_FUNCTION(0, 90),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO90"),
		MTK_FUNCTION(1, "DISP_PWM"),
		MTK_FUNCTION(2, "PWM1")
	),
	MTK_PIN(
 	 	91, "WB_RSTB",
		MTK_EINT_FUNCTION(0, 91),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI91"),
		MTK_FUNCTION(1, "WB_RSTB"),
		MTK_FUNCTION(7, "DBG_MON_A[27]")
	),
	MTK_PIN(
 	 	92, "KPROW1",
		MTK_EINT_FUNCTION(0, 92),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI92"),
		MTK_FUNCTION(1, "KROW1"),
		MTK_FUNCTION(2, "IDDIG"),
		MTK_FUNCTION(7, "DBG_MON_A[28]")
	),
	MTK_PIN(
 	 	93, "KPROW2",
		MTK_EINT_FUNCTION(0, 93),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI93"),
		MTK_FUNCTION(1, "KROW2"),
		MTK_FUNCTION(2, "DRV_VBUS"),
		MTK_FUNCTION(7, "DBG_MON_A[29]")
	),
	MTK_PIN(
 	 	94, "F2W_DATA",
		MTK_EINT_FUNCTION(0, 94),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI94"),
		MTK_FUNCTION(1, "F2W_DATA"),
		MTK_FUNCTION(7, "DBG_MON_A[30]")
	),
	MTK_PIN(
 	 	95, "F2W_CLK",
		MTK_EINT_FUNCTION(0, 95),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI95"),
		MTK_FUNCTION(1, "F2W_CLK"),
		MTK_FUNCTION(7, "DBG_MON_A[31]")
	),
	MTK_PIN(
 	 	96, "WB_SCLK",
		MTK_EINT_FUNCTION(0, 96),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI96"),
		MTK_FUNCTION(1, "WB_SCLK"),
		MTK_FUNCTION(7, "DBG_MON_A[32]")
	),
	MTK_PIN(
 	 	97, "WB_SDATA",
		MTK_EINT_FUNCTION(0, 97),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI97"),
		MTK_FUNCTION(1, "WB_SDATA")
	),
	MTK_PIN(
 	 	98, "WB_SEN",
		MTK_EINT_FUNCTION(0, 98),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI98"),
		MTK_FUNCTION(1, "WB_SEN")
	),
	MTK_PIN(
 	 	99, "WB_CRTL0",
		MTK_EINT_FUNCTION(0, 99),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI99"),
		MTK_FUNCTION(1, "WB_CRTL0"),
		MTK_FUNCTION(2, "dfd_ntrst_xi")
	),
	MTK_PIN(
 	 	100, "WB_CRTL1",
		MTK_EINT_FUNCTION(0, 100),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPI100"),
		MTK_FUNCTION(1, "WB_CRTL1"),
		MTK_FUNCTION(1, "dfd_tms_xi")
	),
	MTK_PIN(
 	 	101, "WB_CRTL2",
		MTK_EINT_FUNCTION(0, 101),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO101"),
		MTK_FUNCTION(1, "WB_CRTL2"),
		MTK_FUNCTION(2, "dfd_tck_xi")
	),
	MTK_PIN(
 	 	102, "WB_CRTL3",
		MTK_EINT_FUNCTION(0, 102),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO102"),
		MTK_FUNCTION(1, "WB_CRTL3"),
		MTK_FUNCTION(2, "dfd_tdi_xi")
	),
	MTK_PIN(
 	 	103, "WB_CRTL4",
		MTK_EINT_FUNCTION(0, 103),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO103"),
		MTK_FUNCTION(1, "WB_CRTL4"),
		MTK_FUNCTION(2, "dfd_tdo")
	),
	MTK_PIN(
 	 	104, "WB_CRTL5",
		MTK_EINT_FUNCTION(0, 104),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO104"),
		MTK_FUNCTION(1, "WB_CRTL5")
	),
	MTK_PIN(
 	 	105, "I2S_DATA_IN",
		MTK_EINT_FUNCTION(0, 105),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO105"),
		MTK_FUNCTION(1, "I2SIN1_DATA_IN"),
		MTK_FUNCTION(2, "PCM_RX"),
		MTK_FUNCTION(3, "I2SOUT_DATA_OUT"),
		MTK_FUNCTION(4, "DAC_DAT_OUT"),
		MTK_FUNCTION(5, "PWM0"),
		MTK_FUNCTION(7, "DBG_MON_B_18")
	),
	MTK_PIN(
 	 	106, "I2S_LRCK",
		MTK_EINT_FUNCTION(0, 106),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO106"),
		MTK_FUNCTION(1, "I2SIN1_LRCK"),
		MTK_FUNCTION(2, "PCM_SYNC"),
		MTK_FUNCTION(3, "I2SOUT_LRCK"),
		MTK_FUNCTION(4, "DAC_WS"),
		MTK_FUNCTION(5, "PWM3"),
		MTK_FUNCTION(7, "DBG_MON_B_19")
	),
	MTK_PIN(
 	 	107, "I2S_BCK",
		MTK_EINT_FUNCTION(0, 107),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO107"),
		MTK_FUNCTION(1, "I2SIN1_BCK2"),
		MTK_FUNCTION(2, "PCM_CLK1"),
		MTK_FUNCTION(3, "I2SOUT_BCK"),
		MTK_FUNCTION(4, "DAC_CK"),
		MTK_FUNCTION(5, "PWM4"),
		MTK_FUNCTION(7, "DBG_MON_B_20")
	),
	MTK_PIN(
 	 	108, "URXD0",
		MTK_EINT_FUNCTION(0, 108),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO108"),
		MTK_FUNCTION(1, "URXD0"),
		MTK_FUNCTION(2, "UTXD0"),
		MTK_FUNCTION(3, "MD_URXD"),
		MTK_FUNCTION(7, "DBG_MON_B_21")
	),
	MTK_PIN(
 	 	109, "UTXD0",
		MTK_EINT_FUNCTION(0, 109),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO109"),
		MTK_FUNCTION(1, "UTXD0"),
		MTK_FUNCTION(2, "URXD0"),
		MTK_FUNCTION(3, "MD_UTXD"),
		MTK_FUNCTION(4, "TDD_TXD"),
		MTK_FUNCTION(7, "DBG_MON_B_22")
	),
	MTK_PIN(
 	 	110, "URXD1",
		MTK_EINT_FUNCTION(0, 110),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO110"),
		MTK_FUNCTION(1, "URXD1"),
		MTK_FUNCTION(2, "UTXD1"),
		MTK_FUNCTION(3, "MD_URXD"),
		MTK_FUNCTION(7, "DBG_MON_B_23")
	),
	MTK_PIN(
 	 	111, "UTXD1",
		MTK_EINT_FUNCTION(0, 111),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO111"),
		MTK_FUNCTION(1, "UTXD1"),
		MTK_FUNCTION(2, "URXD1"),
		MTK_FUNCTION(3, "MD_UTXD"),
		MTK_FUNCTION(4, "TDD_TXD"),
		MTK_FUNCTION(7, "DBG_MON_B_24")
	),
	MTK_PIN(
 	 	112, "LCM_RST",
		MTK_EINT_FUNCTION(0, 112),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO112"),
		MTK_FUNCTION(1, "LCM_RST"),
		MTK_FUNCTION(7, "DBG_MON_B_25")
	),
	MTK_PIN(
 	 	113, "DSI_TE",
		MTK_EINT_FUNCTION(0, 113),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO113"),
		MTK_FUNCTION(1, "DSI_TE"),
		MTK_FUNCTION(7, "DBG_MON_B_26")
	),
	MTK_PIN(
 	 	114, "MSDC2_CMD",
		MTK_EINT_FUNCTION(0, 114),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO114"),
		MTK_FUNCTION(1, "MSDC2_CMD"),
		MTK_FUNCTION(7, "DBG_MON_B_27")
	),
	MTK_PIN(
 	 	115, "MSDC2_CLK",
		MTK_EINT_FUNCTION(0, 115),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO115"),
		MTK_FUNCTION(1, "MSDC2_CLK"),
		MTK_FUNCTION(2, "SCL1"),
		MTK_FUNCTION(4, "NLD8"),
		MTK_FUNCTION(7, "DBG_MON_B_28")
	),
	MTK_PIN(
 	 	116, "MSDC2_DAT0",
		MTK_EINT_FUNCTION(0, 116),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO116"),
		MTK_FUNCTION(1, "MSDC2_DAT0"),
		MTK_FUNCTION(4, "NLD0"),
		MTK_FUNCTION(5, "UTXD0"),
		MTK_FUNCTION(7, "DBG_MON_B_29")
	),
	MTK_PIN(
 	 	117, "MSDC2_DAT1",
		MTK_EINT_FUNCTION(0, 117),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO117"),
		MTK_FUNCTION(1, "MSDC2_DAT1"),
		MTK_FUNCTION(2, "ANT_SEL3"),
		MTK_FUNCTION(3, "PWM0"),
		MTK_FUNCTION(4, "NLD1"),
		MTK_FUNCTION(5, "URXD0"),
		MTK_FUNCTION(7, "DBG_MON_B_30")
	),
	MTK_PIN(
 	 	118, "MSDC2_DAT2",
		MTK_EINT_FUNCTION(0, 118),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO117"),
		MTK_FUNCTION(1, "MSDC2_DAT2"),
		MTK_FUNCTION(2, "ANT_SEL4"),
		MTK_FUNCTION(3, "SDA2"),
		MTK_FUNCTION(4, "NLD2"),
		MTK_FUNCTION(5, "UTXD1"),
		MTK_FUNCTION(7, "DBG_MON_B_31")
	),
	MTK_PIN(
 	 	119, "MSDC2_DAT3",
		MTK_EINT_FUNCTION(0, 119),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO118"),
		MTK_FUNCTION(1, "MSDC2_DAT3"),
		MTK_FUNCTION(2, "ANT_SEL5"),
		MTK_FUNCTION(3, "SCL2"),
		MTK_FUNCTION(4, "NLD3"),
		MTK_FUNCTION(5, "URXD1"),
		MTK_FUNCTION(7, "DBG_MON_B_32")
	),
	MTK_PIN(
 	 	120, "CMDAT0",
		MTK_EINT_FUNCTION(0, 120),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO119"),
		MTK_FUNCTION(1, "CMDAT0"),
		MTK_FUNCTION(2, "CMCSD0")
	),
	MTK_PIN(
 	 	121, "CMDAT1",
		MTK_EINT_FUNCTION(0, 121),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO121"),
		MTK_FUNCTION(1, "CMDAT1"),
		MTK_FUNCTION(2, "CMCSD1")
	),
	MTK_PIN(
 	 	122, "CMMCLK",
		MTK_EINT_FUNCTION(0, 122),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO122"),
		MTK_FUNCTION(1, "CMMCLK")
	),
	MTK_PIN(
 	 	123, "CMPCLK",
		MTK_EINT_FUNCTION(0, 123),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO123"),
		MTK_FUNCTION(1, "CMPCLK"),
		MTK_FUNCTION(2, "CMCSK")
	),
	MTK_PIN(
 	 	124, "MSDC1_CMD",
		MTK_EINT_FUNCTION(0, 124),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO124"),
		MTK_FUNCTION(1, "MSDC1_CMD")
	),
	MTK_PIN(
 	 	125, "MSDC1_CLK",
		MTK_EINT_FUNCTION(0, 125),
		DRV_GRP2,
		MTK_FUNCTION(0, "GPIO125"),
		MTK_FUNCTION(1, "MSDC1_CLK")
	),
	MTK_PIN(
 	 	126, "MSDC1_DAT0",
		MTK_EINT_FUNCTION(0, 126),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO126"),
		MTK_FUNCTION(1, "MSDC1_DAT0")
	),
	MTK_PIN(
 	 	127, "MSDC1_DAT1",
		MTK_EINT_FUNCTION(0, 127),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO127"),
		MTK_FUNCTION(1, "MSDC1_DAT1")
	),
	MTK_PIN(
 	 	128, "MSDC1_DAT2",
		MTK_EINT_FUNCTION(0, 128),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO128"),
		MTK_FUNCTION(1, "MSDC1_DAT2")
	),
	MTK_PIN(
 	 	129, "MSDC1_DAT3",
		MTK_EINT_FUNCTION(0, 129),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO129"),
		MTK_FUNCTION(1, "MSDC1_DAT3")
	),
	MTK_PIN(
 	 	130, "MSDC0_DAT7",
		MTK_EINT_FUNCTION(0, 130),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO130"),
		MTK_FUNCTION(1, "MSDC0_DAT7"),
		MTK_FUNCTION(4, "NALE")
	),
	MTK_PIN(
 	 	131, "MSDC0_DAT6",
		MTK_EINT_FUNCTION(0, 131),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO131"),
		MTK_FUNCTION(1, "MSDC0_DAT6"),
		MTK_FUNCTION(4, "NCLE")
	),
	MTK_PIN(
 	 	132, "MSDC0_DAT5",
		MTK_EINT_FUNCTION(0, 132),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO132"),
		MTK_FUNCTION(1, "MSDC0_DAT5"),
		MTK_FUNCTION(4, "NLD4")
	),
	MTK_PIN(
 	 	133, "MSDC0_DAT4",
		MTK_EINT_FUNCTION(0, 133),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO133"),
		MTK_FUNCTION(1, "MSDC0_DAT4"),
		MTK_FUNCTION(4, "NLD5")
	),
	MTK_PIN(
 	 	134, "MSDC0_RSTB",
		MTK_EINT_FUNCTION(0, 134),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO134"),
		MTK_FUNCTION(1, "MSDC0_RSTB"),
		MTK_FUNCTION(4, "NLD10")
	),
	MTK_PIN(
 	 	135, "MSDC0_CMD",
		MTK_EINT_FUNCTION(0, 135),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO135"),
		MTK_FUNCTION(1, "MSDC0_CMD"),
		MTK_FUNCTION(4, "NRNB")
	),
	MTK_PIN(
 	 	136, "MSDC0_CLK",
		MTK_EINT_FUNCTION(0, 136),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO136"),
		MTK_FUNCTION(1, "MSDC0_CLK"),
		MTK_FUNCTION(4, "NREB")
	),
	MTK_PIN(
 	 	137, "MSDC0_DAT3",
		MTK_EINT_FUNCTION(0, 137),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO137"),
		MTK_FUNCTION(1, "MSDC0_DAT3"),
		MTK_FUNCTION(4, "NLD7"),
		MTK_FUNCTION(7, "DBG_MON_B_1")
	),
	MTK_PIN(
 	 	138, "MSDC0_DAT2",
		MTK_EINT_FUNCTION(0, 138),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO138"),
		MTK_FUNCTION(1, "MSDC0_DAT2"),
		MTK_FUNCTION(4, "NLD14")
	),
	MTK_PIN(
 	 	139, "MSDC0_DAT1",
		MTK_EINT_FUNCTION(0, 139),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO139"),
		MTK_FUNCTION(1, "MSDC0_DAT1"),
		MTK_FUNCTION(4, "NLD11"),
		MTK_FUNCTION(7, "DBG_MON_B_2")
	),
	MTK_PIN(
 	 	140, "MSDC0_DAT0",
		MTK_EINT_FUNCTION(0, 140),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO140"),
		MTK_FUNCTION(1, "MSDC0_DAT0"),
		MTK_FUNCTION(4, "WATCHDOG")
	),
	MTK_PIN(
 	 	141, "RDP0_A",
		MTK_EINT_FUNCTION(0, 141),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO141"),
		MTK_FUNCTION(1, "RDP0_A"),
		MTK_FUNCTION(2, "CMVSYNC")
	),
	MTK_PIN(
 	 	142, "RDN0_A",
		MTK_EINT_FUNCTION(0, 142),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO142"),
		MTK_FUNCTION(1, "RDN0_A"),
		MTK_FUNCTION(2, "CMHSYNC")
	),
	MTK_PIN(
 	 	143, "RDP1_A",
		MTK_EINT_FUNCTION(0, 143),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO143"),
		MTK_FUNCTION(1, "RDP1_A"),
		MTK_FUNCTION(2, "CMDAT3"),
		MTK_FUNCTION(3, "CMCSD3")
	),
	MTK_PIN(
 	 	144, "RDN1_A",
		MTK_EINT_FUNCTION(0, 144),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO144"),
		MTK_FUNCTION(1, "RDN1_A"),
		MTK_FUNCTION(2, "CMDAT2"),
		MTK_FUNCTION(3, "CMCSD2")
	),
	MTK_PIN(
 	 	145, "RCP_A",
		MTK_EINT_FUNCTION(0, 145),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO145"),
		MTK_FUNCTION(1, "RCP_A"),
		MTK_FUNCTION(2, "CMDAT7")
	),
	MTK_PIN(
 	 	146, "RCN_A",
		MTK_EINT_FUNCTION(0, 146),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO146"),
		MTK_FUNCTION(1, "RCN_A"),
		MTK_FUNCTION(2, "CMDAT6")
	),
	MTK_PIN(
 	 	147, "RDP0",
		MTK_EINT_FUNCTION(0, 147),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO147"),
		MTK_FUNCTION(1, "RDP0")

	),
	MTK_PIN(
 	 	148, "RDN0",
		MTK_EINT_FUNCTION(0, 148),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO148"),
		MTK_FUNCTION(1, "RDN0")
	),
	MTK_PIN(
 	 	149, "RDP1",
		MTK_EINT_FUNCTION(0, 149),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO149"),
		MTK_FUNCTION(1, "RDP1")
	),
	MTK_PIN(
 	 	150, "RDN1",
		MTK_EINT_FUNCTION(0, 150),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO150"),
		MTK_FUNCTION(1, "RDN1")
	),
	MTK_PIN(
 	 	151, "RCP",
		MTK_EINT_FUNCTION(0, 151),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO151"),
		MTK_FUNCTION(1, "RCP")
	),
	MTK_PIN(
 	 	152, "RCN",
		MTK_EINT_FUNCTION(0, 152),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO152"),
		MTK_FUNCTION(1, "RCN")
	),
	MTK_PIN(
 	 	153, "RDP2",
		MTK_EINT_FUNCTION(0, 153),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO153"),
		MTK_FUNCTION(1, "RDP2"),
		MTK_FUNCTION(2, "CMDAT9")
	),
	MTK_PIN(
 	 	154, "RDN2",
		MTK_EINT_FUNCTION(0, 154),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO154"),
		MTK_FUNCTION(1, "RDN2"),
		MTK_FUNCTION(2, "CMDAT8")
	),
	MTK_PIN(
 	 	155, "RDP3",
		MTK_EINT_FUNCTION(0, 155),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO155"),
		MTK_FUNCTION(1, "RDP3"),
		MTK_FUNCTION(2, "CMDAT5")
	),
	MTK_PIN(
 	 	156, "RDN3",
		MTK_EINT_FUNCTION(0, 156),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO156"),
		MTK_FUNCTION(1, "RDN3"),
		MTK_FUNCTION(2, "CMDAT4")
	),
	MTK_PIN(
 	 	157, "TDP0",
		MTK_EINT_FUNCTION(0, 157),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO157"),
		MTK_FUNCTION(1, "TDP0")
	),
	MTK_PIN(
 	 	158, "TDN0",
		MTK_EINT_FUNCTION(0, 158),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO158"),
		MTK_FUNCTION(1, "TDN0")
	),
	MTK_PIN(
 	 	159, "TDP1",
		MTK_EINT_FUNCTION(0, 159),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO159"),
		MTK_FUNCTION(1, "TDP1")
	),
	MTK_PIN(
 	 	160, "TDN1",
		MTK_EINT_FUNCTION(0, 160),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO160"),
		MTK_FUNCTION(1, "TDN1")
	),
	MTK_PIN(
 	 	161, "TCP",
		MTK_EINT_FUNCTION(0, 161),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO161"),
		MTK_FUNCTION(1, "TCP")
	),
	MTK_PIN(
 	 	162, "TCN",
		MTK_EINT_FUNCTION(0, 162),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO162"),
		MTK_FUNCTION(1, "TCN")
	),
	MTK_PIN(
 	 	163, "TDP2",
		MTK_EINT_FUNCTION(0, 163),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO163"),
		MTK_FUNCTION(1, "TDP2")
	),
	MTK_PIN(
 	 	164, "TDN2",
		MTK_EINT_FUNCTION(0, 164),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO164"),
		MTK_FUNCTION(1, "TDN2")
	),
	MTK_PIN(
 	 	165, "TDP3",
		MTK_EINT_FUNCTION(0, 165),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO165"),
		MTK_FUNCTION(1, "TDP3")
	),
	MTK_PIN(
 	 	166, "TDN3",
		MTK_EINT_FUNCTION(0, 166),
		DRV_FIXED,
		MTK_FUNCTION(0, "GPIO166"),
		MTK_FUNCTION(1, "TDN3")
	),
	MTK_PIN(
 	 	167, "KPCOL1",
		MTK_EINT_FUNCTION(0, 167),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO167"),
		MTK_FUNCTION(1, "KCOL1")
	),
	MTK_PIN(
 	 	168, "KPCOL2",
		MTK_EINT_FUNCTION(0, 168),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO168"),
		MTK_FUNCTION(1, "KCOL2")
	)

};

#endif /* __PINCTRL_MTK_MT6582_H */
