/* SPDX-License-Identifier: (GPL-2.0+ OR BSD-2-Clause) */

#ifndef _DT_BINDINGS_CLK_MT6572_H
#define _DT_BINDINGS_CLK_MT6572_H

/* TOPCKGEN */
#define CLK_TOP_SC_26M_SEL 0
#define CLK_TOP_UNIV_48M_SEL 1

#define CLK_TOP_MPLL_D2 2
#define CLK_TOP_MPLL_D3 3
#define CLK_TOP_MPLL_D5 4
#define CLK_TOP_MPLL_D7 5
#define CLK_TOP_MPLL_D4 6
#define CLK_TOP_MPLL_D6 7
#define CLK_TOP_MPLL_D10 8
#define CLK_TOP_MPLL_D8 9
#define CLK_TOP_MPLL_D12 10
#define CLK_TOP_MPLL_D20 11
#define CLK_TOP_MPLL_D24 12
#define CLK_TOP_UPLL_D2 13
#define CLK_TOP_UPLL_D3 14
#define CLK_TOP_UPLL_D5 15
#define CLK_TOP_UPLL_D7 16
#define CLK_TOP_UPLL_D4 17
#define CLK_TOP_UPLL_D6 18
#define CLK_TOP_UPLL_D10 19
#define CLK_TOP_UPLL_D8 20
#define CLK_TOP_UPLL_D12 21
#define CLK_TOP_UPLL_D20 22
#define CLK_TOP_UPLL_D16 23
#define CLK_TOP_UPLL_D24 24

#define CLK_TOP_UART0_SEL 25
#define CLK_TOP_EMI2X_SEL 26
#define CLK_TOP_AXI_SEL 27
#define CLK_TOP_MFG_SEL 28
#define CLK_TOP_MSDC0_SEL 29
#define CLK_TOP_SPI_NAND_SEL 30
#define CLK_TOP_CAM_SEL 31
#define CLK_TOP_PWM_SEL 32
#define CLK_TOP_UART1_SEL 33
#define CLK_TOP_MSDC1_SEL 34
#define CLK_TOP_SPM_SEL 35
#define CLK_TOP_PMIC_SPI_SEL 36
#define CLK_TOP_AUDIO_INTBUS_SEL 37

#define CLK_TOP_PWM 38
#define CLK_TOP_CAM 39
#define CLK_TOP_MFG 40
#define CLK_TOP_SPM 41
#define CLK_TOP_UART0 42
#define CLK_TOP_UART1 43
#define CLK_TOP_MSDC0 44
#define CLK_TOP_MSDC1 45
#define CLK_TOP_PMIC_WRAP 46
#define CLK_TOP_PMIC_SPI 47
#define CLK_TOP_APXGPT 48

#define CLK_APMIXED_ARMPLL 0
#define CLK_APMIXED_MAINPLL 1
#define CLK_APMIXED_UNIVPLL 2
#define CLK_APMIXED_WHPLL 3

#endif /* _DT_BINDINGS_CLK_MT6572_H */
