/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Author: Akari Tsuyukusa <akkun11.open@gmail.com>
 */

#ifndef _DT_BINDINGS_CLK_MEDIATEK_MT6589_CLK_H
#define _DT_BINDINGS_CLK_MEDIATEK_MT6589_CLK_H

/* APMIXEDSYS */
#define CLK_APMIXED_ARMPLL	0
#define CLK_APMIXED_MAINPLL	1
#define CLK_APMIXED_UNIVPLL	2
#define CLK_APMIXED_MMPLL	3
#define CLK_APMIXED_ISPPLL	4
#define CLK_APMIXED_MSDCPLL	5
#define CLK_APMIXED_TVDPLL	6
#define CLK_APMIXED_LVDSPLL	7

#define CLK_APMIXED_ARMPLL_1300M	8

#define CLK_APMIXED_MAINPLL_806M	9
#define CLK_APMIXED_MAINPLL_537P3M	10
#define CLK_APMIXED_MAINPLL_322P4M	11
#define CLK_APMIXED_MAINPLL_230P3M	12

#define CLK_APMIXED_UNIVPLL_624M	13
#define CLK_APMIXED_UNIVPLL_416M	14
#define CLK_APMIXED_UNIVPLL_249P6M	15
#define CLK_APMIXED_UNIVPLL_178P3M	16
#define CLK_APMIXED_UNIVPLL_48M		17
#define CLK_APMIXED_UNIVPLL_USB_48M	18

#define CLK_APMIXED_MMPLL_D2		19
/* GPU: 476MHz */
#define CLK_APMIXED_MMPLL_D3		20
/* GPU: 286MHz */
#define CLK_APMIXED_MMPLL_D5		21
#define CLK_APMIXED_MMPLL_D7		22

#define CLK_APMIXED_ISPPLL_208M		23

#define CLK_APMIXED_MSDCPLL_208M	24

#define CLK_APMIXED_TVDPLL_148P5M	25

#define CLK_APMIXED_LVDSPLL_180M	26

#define CLK_APMIXED_NR_CLK		27


/* TOPCKGEN */
#define CLK_TOP_CLK_NULL	0

#define CLK_TOP_CLKPH_MCK	1
#define CLK_TOP_CPUM_TCK_IN	2

/* GPU: 403MHz */
#define CLK_TOP_SYSPLL_D2	3
/* MAINPLL / 3 / 2 = GPU: 268MHz */
#define CLK_TOP_SYSPLL_D3	4
#define CLK_TOP_SYSPLL_D3P5	5
/* MAINPLL / 2 / 4 */
#define CLK_TOP_SYSPLL_D4	6
#define CLK_TOP_SYSPLL_D5	7
/* MAINPLL /2 / 6 */
#define CLK_TOP_SYSPLL_D6	8
#define CLK_TOP_SYSPLL_D8	9
#define CLK_TOP_SYSPLL_D10	10
#define CLK_TOP_SYSPLL_D16	11
#define CLK_TOP_SYSPLL_D24	12

#define CLK_TOP_UNIVPLL_D3	13
/* UNIVPLL / 5 */
#define CLK_TOP_UNIVPLL_D5	14
#define CLK_TOP_UNIVPLL_D7	15
#define CLK_TOP_UNIVPLL_D10	16
#define CLK_TOP_UNIVPLL_D26	17

/* GPU: 312MHz */
#define CLK_TOP_UNIVPLL1_D2	18
/* GPU: 156MHz */
#define CLK_TOP_UNIVPLL1_D4	19
#define CLK_TOP_UNIVPLL1_D6	20
#define CLK_TOP_UNIVPLL1_D8	21
#define CLK_TOP_UNIVPLL1_D10	22

/* UNIVPLL / 3 / 2 */
#define CLK_TOP_UNIVPLL2_D2	23
/* unknown */
#define CLK_TOP_UNIVPLL2_D4	24
#define CLK_TOP_UNIVPLL2_D6	25
#define CLK_TOP_UNIVPLL2_D8	26

/* GPU: 357MHz */
#define CLK_TOP_MMPLL_D4	27
/* GPU: 238MHz */
#define CLK_TOP_MMPLL_D6	28

#define CLK_TOP_LVDSPLL		29
#define CLK_TOP_LVDSPLL_D2	30
#define CLK_TOP_LVDSPLL_D4	31
#define CLK_TOP_LVDSPLL_D8	32

#define CLK_TOP_MEMPLL_MCK_D4	33

/* MUXs */
/* CLK_CFG_0 */
#define CLK_TOP_MUX_AXI		34
#define CLK_TOP_MUX_SMI		35
#define CLK_TOP_MUX_MFG		36
#define CLK_TOP_MUX_IRDA	37

/* CLK_CFG_1 */
#define CLK_TOP_MUX_CAM		38
#define CLK_TOP_MUX_AUDINTBUS	39
#define CLK_TOP_MUX_JPG		40
#define CLK_TOP_MUX_DISP	41

/* CLK_CFG_2 */
#define CLK_TOP_MUX_MSDC1	42
#define CLK_TOP_MUX_MSDC2	43
#define CLK_TOP_MUX_MSDC3	44
#define CLK_TOP_MUX_MSDC4	45

/* CLK_CFG_3 */
#define CLK_TOP_MUX_USB20	46

/* CLK_CFG_4 */
#define CLK_TOP_MUX_HYD		47
#define CLK_TOP_MUX_VENC	48
#define CLK_TOP_MUX_SPI		49
#define CLK_TOP_MUX_UART	50

/* CLK_CFG_6 */
#define CLK_TOP_MUX_MEM		51
#define CLK_TOP_MUX_CAMTG	52
#define CLK_TOP_MUX_FD		53
#define CLK_TOP_MUX_AUDIO	54

/* CLK_CFG_7 */
#define CLK_TOP_MUX_FIX		55
#define CLK_TOP_MUX_VDEC	56
#define CLK_TOP_MUX_DPILVDS	57

/* CLK_CFG_8 */
#define CLK_TOP_MUX_PMICSPI	58
#define CLK_TOP_MUX_MSDC0	59
#define CLK_TOP_MUX_SMI_MFG_AS	60

#define CLK_TOPCK_PMICSPI	61


/* INFRACFG */
#define CLK_INFRA_MUX1		0

#define CLK_INFRA_DBGCLK	1
#define CLK_INFRA_SMI		2
#define CLK_INFRA_SPI0		3
#define CLK_INFRA_AUDIO		4
#define CLK_INFRA_CEC   	5
#define CLK_INFRA_MFGAXI	6
#define CLK_INFRA_M4U		7
#define CLK_INFRA_MD1MCUAXI	8
#define CLK_INFRA_MD1HWMIXAXI	9
#define CLK_INFRA_MD1AHB	10
#define CLK_INFRA_MD2MCUAXI	11
#define CLK_INFRA_MD2HWMIXAXI	12
#define CLK_INFRA_MD2AHB	13
#define CLK_INFRA_CPUM		14
#define CLK_INFRA_KP		15
#define CLK_INFRA_CCIF0		16
#define CLK_INFRA_CCIF1		17
#define CLK_INFRA_PMICSPI	18
#define CLK_INFRA_PMICWRAP	19


/* PERICFG */
#define CLK_PERI0_NFI		0
#define CLK_PERI0_THERM		1
#define CLK_PERI0_PWM1		2
#define CLK_PERI0_PWM2		3
#define CLK_PERI0_PWM3		4
#define CLK_PERI0_PWM4		5
#define CLK_PERI0_PWM5		6
#define CLK_PERI0_PWM6		7
#define CLK_PERI0_PWM7		8
#define CLK_PERI0_PWM		9
#define CLK_PERI0_USB0		10
#define CLK_PERI0_USB1		11
#define CLK_PERI0_APDMA		12
#define CLK_PERI0_MSDC0		13
#define CLK_PERI0_MSDC1		14
#define CLK_PERI0_MSDC2		15
#define CLK_PERI0_MSDC3		16
#define CLK_PERI0_MSDC4		17
#define CLK_PERI0_APHIF		18
#define CLK_PERI0_MDHIF		19
#define CLK_PERI0_NLI		20
#define CLK_PERI0_IRDA		21
#define CLK_PERI0_UART0		22
#define CLK_PERI0_UART1		23
#define CLK_PERI0_UART2		24
#define CLK_PERI0_UART3		25
#define CLK_PERI0_I2C0		26
#define CLK_PERI0_I2C1		27
#define CLK_PERI0_I2C2		28
#define CLK_PERI0_I2C3		29
#define CLK_PERI0_I2C4		30
#define CLK_PERI0_I2C5		31

#define CLK_PERI1_I2C6		32
#define CLK_PERI1_PWRAP		33
#define CLK_PERI1_AUXADC	34
#define CLK_PERI1_SPI1		35
#define CLK_PERI1_FHCTL		36

#define CLK_PERI_MUX_UART0	37
#define CLK_PERI_MUX_UART1	38
#define CLK_PERI_MUX_UART2	39
#define CLK_PERI_MUX_UART3	40


/* DISP */
#define CLK_DISP0_LARB2_SMI	0
#define CLK_DISP0_ROT_ENGINE	1
#define CLK_DISP0_ROT_SMI	2
#define CLK_DISP0_SCL		3
#define CLK_DISP0_OVL_ENGINE	4
#define CLK_DISP0_OVL_SMI	5
#define CLK_DISP0_COLOR		6
#define CLK_DISP0_2DSHP		7
#define CLK_DISP0_BLS		8
#define CLK_DISP0_WDMA0_ENGINE	9
#define CLK_DISP0_WDMA0_SMI	10
#define CLK_DISP0_WDMA1_ENGINE	11
#define CLK_DISP0_WDMA1_SMI	12
#define CLK_DISP0_RDMA0_ENGINE	13
#define CLK_DISP0_RDMA0_SMI	14
#define CLK_DISP0_RDMA0_OUTPUT	15
#define CLK_DISP0_RDMA1_ENGINE	16
#define CLK_DISP0_RDMA1_SMI	17
#define CLK_DISP0_RDMA1_OUTPUT	18
#define CLK_DISP0_GAMMA_ENGINE	19
#define CLK_DISP0_GAMMA_PIXEL	20
#define CLK_DISP0_CMDQ_ENGINE	21
#define CLK_DISP0_CMDQ_SMI	22
#define CLK_DISP0_G2D_ENGINE	23
#define CLK_DISP0_G2D_SMI	24

#define CLK_DISP1_DBI_ENGINE	25
#define CLK_DISP1_DBI_SMI	26
#define CLK_DISP1_DBI_OUTPUT	27
#define CLK_DISP1_DSI_ENGINE	28
#define CLK_DISP1_DSI_DIGITAL	29
#define CLK_DISP1_DSI_DIGITAL_LANE	30
#define CLK_DISP1_DPI0		31
#define CLK_DISP1_DPI1		32
#define CLK_DISP1_LCD		33
#define CLK_DISP1_SLCD		34


/* IMG */
#define CLK_IMAGE_LARB3_SMI	0
#define CLK_IMAGE_LARB4_SMI	1
#define CLK_IMAGE_COMMON_SMI	2
#define CLK_IMAGE_CAM_SMI	3
#define CLK_IMAGE_CAM_CAM	4
#define CLK_IMAGE_SEN_TG	5
#define CLK_IMAGE_SEN_CAM	6
#define CLK_IMAGE_JPGD_SMI	7
#define CLK_IMAGE_JPGD_JPG	8
#define CLK_IMAGE_JPGE_SMI	9
#define CLK_IMAGE_JPGE_JPG	10
#define CLK_IMAGE_FPC		11


/* MFG */
#define CLK_MFG_AXI		0
#define CLK_MFG_MEM		1
#define CLK_MFG_G3D		2
#define CLK_MFG_HYD		3


/* AUD */
#define CLK_AUDIO_AFE		0
#define CLK_AUDIO_I2S		1


/* VDEC */
#define CLK_VDEC0_VDE		0

#define CLK_VDEC1_SMI		1


/* VENC */
#define CLK_VENC_VEN		0

#endif
