// SPDX-License-Identifier: GPL-2.0-only
/*
 * Author: akku <akkun11.open@gmail.com>
 */

/* clock IDs from mt_clkmgr.h */


/* APMIXEDSYS */
#define CLK_APMIXED_ARMPLL	0
#define CLK_APMIXED_MAINPLL	1
#define CLK_APMIXED_MSDCPLL	2
#define CLK_APMIXED_TVDPLL	3
#define CLK_APMIXED_LVDSPLL	4
#define CLK_APMIXED_UNIVPLL	5
#define CLK_APMIXED_MMPLL	6
#define CLK_APMIXED_ISPPLL	7
#define CLK_APMIXED_NR_CLK	8


/* TOPCKGEN */
#define CLK_TOP_SYSPLL		1
/* GPU: 403MHz */
#define CLK_TOP_SYSPLL_D2	2
/* MAINPLL / 3 / 2 = GPU: 268MHz */
#define CLK_TOP_SYSPLL_D3	3
/* MAINPLL / 2 / 4 */
#define CLK_TOP_SYSPLL_D4	4
/* MAINPLL /2 / 6 */
#define CLK_TOP_SYSPLL_D6	6

/* must be univpll2 parent */
#define CLK_TOP_UNIVPLL_D3	16
/* UNIVPLL / 5 */
#define CLK_TOP_UNIVPLL_D5	7
/* GPU: 312MHz */
#define CLK_TOP_UNIVPLL1_D2	8
/* GPU: 156MHz */
#define CLK_TOP_UNIVPLL1_D4	9
/* UNIVPLL / 3 / 2 */
#define CLK_TOP_UNIVPLL2_D2	10
/* unknown */
#define CLK_TOP_UNIVPLL2_D4	15

/* GPU: 476MHz */
#define CLK_TOP_MMPLL_D3	11
/* GPU: 357MHz */
#define CLK_TOP_MMPLL_D4	12
/* GPU: 286MHz */
#define CLK_TOP_MMPLL_D5	13
/* GPU: 238MHz */
#define CLK_TOP_MMPLL_D6	14

/* MUXs */
/* CLK_CFG_0 */
#define CLK_TOP_MUX_MFG	0
#define CLK_TOP_MUX_IRDA	1

/* CLK_CFG_1 */
#define CLK_TOP_MUX_CAM	2
#define CLK_TOP_MUX_AUDINTBUS	3
#define CLK_TOP_MUX_JPG	4
#define CLK_TOP_MUX_DISP	5

/* CLK_CFG_2 */
#define CLK_TOP_MUX_MSDC1	6
#define CLK_TOP_MUX_MSDC2	7
#define CLK_TOP_MUX_MSDC3	8
#define CLK_TOP_MUX_MSDC4	9

/* CLK_CFG_3 */
#define CLK_TOP_MUX_USB20	10

/* CLK_CFG_4 */
#define CLK_TOP_MUX_HYD	11
#define CLK_TOP_MUX_VENC	12
#define CLK_TOP_MUX_SPI	13
#define CLK_TOP_MUX_UART	14

/* CLK_CFG_6 */
#define CLK_TOP_MUX_CAMTG	15
// #define CLK_TOP_MUX_FD	16 */
#define CLK_TOP_MUX_AUDIO	16

/* CLK_CFG_7 */
#define CLK_TOP_MUX_VDEC	17
#define CLK_TOP_MUX_DPILVDS	18

/* CLK_CFG_8 */
#define CLK_TOP_MUX_PMICSPI	19
#define CLK_TOP_MUX_MSDC0	20
#define CLK_TOP_MUX_SMI_MFG_AS	21


/* INFRACFG */
#define CLK_INFRA_DBGCLK	64
#define CLK_INFRA_SMI		65
#define CLK_INFRA_SPI0	66
#define CLK_INFRA_AUDIO	69
#define CLK_INFRA_CEC	70
#define CLK_INFRA_MFGAXI	71
#define CLK_INFRA_M4U	72
#define CLK_INFRA_MD1MCUAXI	73
#define CLK_INFRA_MD1HWMIXAXI	74
#define CLK_INFRA_MD1AHB	75
#define CLK_INFRA_MD2MCUAXI	76
#define CLK_INFRA_MD2HWMIXAXI	77
#define CLK_INFRA_MD2AHB	78
#define CLK_INFRA_CPUM	79
#define CLK_INFRA_KP	80
#define CLK_INFRA_CCIF0	84
#define CLK_INFRA_CCIF1	85
#define CLK_INFRA_PMICSPI	86
#define CLK_INFRA_PMICWRAP	87


/* PERICFG */
#define CLK_PERI0_NFI	0
#define CLK_PERI0_THERM	1
#define CLK_PERI0_PWM1	2
#define CLK_PERI0_PWM2	3
#define CLK_PERI0_PWM3	4
#define CLK_PERI0_PWM4	5
#define CLK_PERI0_PWM5	6
#define CLK_PERI0_PWM6	7
#define CLK_PERI0_PWM7	8
#define CLK_PERI0_PWM	9
#define CLK_PERI0_USB0	10
#define CLK_PERI0_USB1	11
#define CLK_PERI0_APDMA	12
#define CLK_PERI0_MSDC0	13
#define CLK_PERI0_MSDC1	14
#define CLK_PERI0_MSDC2	15
#define CLK_PERI0_MSDC3	16
#define CLK_PERI0_MSDC4	17
#define CLK_PERI0_APHIF	18
#define CLK_PERI0_MDHIF	19
#define CLK_PERI0_NLI	20
#define CLK_PERI0_IRDA	21
#define CLK_PERI0_UART0	22
#define CLK_PERI0_UART1	23
#define CLK_PERI0_UART2	24
#define CLK_PERI0_UART3	25
#define CLK_PERI0_I2C0	26
#define CLK_PERI0_I2C1	27
#define CLK_PERI0_I2C2	28
#define CLK_PERI0_I2C3	29
#define CLK_PERI0_I2C4	30
#define CLK_PERI0_I2C5	31

#define CLK_PERI1_I2C6	32
#define CLK_PERI1_WRAP	33
#define CLK_PERI1_AUXADC	34
#define CLK_PERI1_SPI1	35
#define CLK_PERI1_FHCTL	36
