// SPDX-License-Identifier: GPL-2.0-only
/*
 * Author: akku <akkun11.open@gmail.com>
 */

/* clock IDs from mt_clkmgr.h */


/* APMIXEDSYS */
#define CLK_APMIXED_ARMPLL	0
#define CLK_APMIXED_MAINPLL	1
#define CLK_APMIXED_MSDCPLL	2
#define CLK_APMIXED_TVDPLL	3
#define CLK_APMIXED_LVDSPLL	4
#define CLK_APMIXED_UNIVPLL	5
#define CLK_APMIXED_MMPLL	6
#define CLK_APMIXED_ISPPLL	7
#define CLK_APMIXED_NR_CLK	8


/* TOPCKGEN */
#define CLK_TOP_CLK_NULL	1

#define CLK_TOP_CLKPH_MCK	11
#define CLK_TOP_CPUM_TCK_IN	12

#define CLK_TOP_SYSPLL		21
#define CLK_TOP_MAINPLL_D3	22
#define CLK_TOP_MAINPLL_D5	23
#define CLK_TOP_MAINPLL_D7	24

/* GPU: 403MHz */
#define CLK_TOP_SYSPLL_D2	31
#define CLK_TOP_SYSPLL_D2P5	32
/* MAINPLL / 3 / 2 = GPU: 268MHz */
#define CLK_TOP_SYSPLL_D3	33
#define CLK_TOP_SYSPLL_D3P5	34
/* MAINPLL / 2 / 4 */
#define CLK_TOP_SYSPLL_D4	35
#define CLK_TOP_SYSPLL_D5	36
/* MAINPLL /2 / 6 */
#define CLK_TOP_SYSPLL_D6	37
#define CLK_TOP_SYSPLL_D8	38
#define CLK_TOP_SYSPLL_D10	39
#define CLK_TOP_SYSPLL_D12	40
#define CLK_TOP_SYSPLL_D16	41
#define CLK_TOP_SYSPLL_D24	42

/* may be univpll1 parent */
#define CLK_TOP_UNIVPLL_D2	51
/* must be univpll2 parent */
#define CLK_TOP_UNIVPLL_D3	52
/* UNIVPLL / 5 */
#define CLK_TOP_UNIVPLL_D5	53
#define CLK_TOP_UNIVPLL_D7	54
#define CLK_TOP_UNIVPLL_D10	55
#define CLK_TOP_UNIVPLL_D26	56

/* GPU: 312MHz */
#define CLK_TOP_UNIVPLL1_D2	61
/* GPU: 156MHz */
#define CLK_TOP_UNIVPLL1_D4	62
#define CLK_TOP_UNIVPLL1_D6	63
#define CLK_TOP_UNIVPLL1_D8	64
#define CLK_TOP_UNIVPLL1_D10	65

/* UNIVPLL / 3 / 2 */
#define CLK_TOP_UNIVPLL2_D2	71
/* unknown */
#define CLK_TOP_UNIVPLL2_D4	72
#define CLK_TOP_UNIVPLL2_D6	73
#define CLK_TOP_UNIVPLL2_D8	74

#define CLK_TOP_MMPLL_D2	81
/* GPU: 476MHz */
#define CLK_TOP_MMPLL_D3	82
/* GPU: 357MHz */
#define CLK_TOP_MMPLL_D4	83
/* GPU: 286MHz */
#define CLK_TOP_MMPLL_D5	84
/* GPU: 238MHz */
#define CLK_TOP_MMPLL_D6	85
#define CLK_TOP_MMPLL_D7	86

#define CLK_TOP_LVDSPLL	91
#define CLK_TOP_LVDSPLL_D2	92
#define CLK_TOP_LVDSPLL_D4	93
#define CLK_TOP_LVDSPLL_D8	94

#define CLK_TOP_LVDSTX_CLKDIG_CT 	101

#define CLK_TOP_TVHDMI_H	111

#define CLK_TOP_HDMITX_CLKDIG_D2	121
#define CLK_TOP_HDMITX_CLKDIG_D3	122

#define CLK_TOP_TVHDMI_D2	131
#define CLK_TOP_TVHDMI_D4	132

#define CLK_TOP_MEMPLL_MCK_D4	141

#define CLK_TOP_APLL	151
#define CLK_TOP_APLL_D4	152
#define CLK_TOP_APLL_D8	153
#define CLK_TOP_APLL_D16	154
#define CLK_TOP_APLL_D24	155

#define CLK_TOP_VPLL_DPIX	161

#define CLK_TOP_AD_ISP_208M_CK	171

#define CLK_TOP_AD_MSDC_H208M_CK	181


/* MUXs */
/* CLK_CFG_0 */
#define CLK_TOP_MUX_AXI	201
#define CLK_TOP_MUX_SMI	202
#define CLK_TOP_MUX_MFG	203
#define CLK_TOP_MUX_IRDA	204

/* CLK_CFG_1 */
#define CLK_TOP_MUX_CAM	205
#define CLK_TOP_MUX_AUDINTBUS	206
#define CLK_TOP_MUX_JPG	207
#define CLK_TOP_MUX_DISP	208

/* CLK_CFG_2 */
#define CLK_TOP_MUX_MSDC1	209
#define CLK_TOP_MUX_MSDC2	210
#define CLK_TOP_MUX_MSDC3	211
#define CLK_TOP_MUX_MSDC4	212

/* CLK_CFG_3 */
#define CLK_TOP_MUX_USB20	213
// 214
// 215
// 216

/* CLK_CFG_4 */
#define CLK_TOP_MUX_HYD	217
#define CLK_TOP_MUX_VENC	218
#define CLK_TOP_MUX_SPI	219
#define CLK_TOP_MUX_UART	220

/* CLK_CFG_6 */
#define CLK_TOP_MUX_MEM	221
#define CLK_TOP_MUX_CAMTG	222
#define CLK_TOP_MUX_FD	223
#define CLK_TOP_MUX_AUDIO	224

/* CLK_CFG_7 */
#define CLK_TOP_MUX_FIX	225
#define CLK_TOP_MUX_VDEC	226
#define CLK_TOP_MUX_DPILVDS	227

/* CLK_CFG_8 */
#define CLK_TOP_MUX_PMICSPI	228
#define CLK_TOP_MUX_MSDC0	229
#define CLK_TOP_MUX_SMI_MFG_AS	230

#define CLK_TOPCK_PMICSPI	301


/* INFRACFG */
#define CLK_INFRA_MUX1		0

#define CLK_INFRA_DBGCLK	1
#define CLK_INFRA_SMI		2
#define CLK_INFRA_SPI0		3
#define CLK_INFRA_AUDIO		4
#define CLK_INFRA_DEVAPC	5
#define CLK_INFRA_MFGAXI	6
#define CLK_INFRA_M4U		7
#define CLK_INFRA_MD1MCUAXI	8
#define CLK_INFRA_MD1HWMIXAXI	9
#define CLK_INFRA_MD1AHB	10
#define CLK_INFRA_MD2MCUAXI	11
#define CLK_INFRA_MD2HWMIXAXI	12
#define CLK_INFRA_MD2AHB	13
#define CLK_INFRA_CPUM		14
#define CLK_INFRA_KP		15
#define CLK_INFRA_CCIF0		16
#define CLK_INFRA_CCIF1		17
#define CLK_INFRA_PMICSPI	18
#define CLK_INFRA_PMICWRAP	19


/* PERICFG */
#define CLK_PERI0_NFI		0
#define CLK_PERI0_THERM		1
#define CLK_PERI0_PWM1		2
#define CLK_PERI0_PWM2		3
#define CLK_PERI0_PWM3		4
#define CLK_PERI0_PWM4		5
#define CLK_PERI0_PWM5		6
#define CLK_PERI0_PWM6		7
#define CLK_PERI0_PWM7		8
#define CLK_PERI0_PWM		9
#define CLK_PERI0_USB0		10
#define CLK_PERI0_USB1		11
#define CLK_PERI0_APDMA		12
#define CLK_PERI0_MSDC0		13
#define CLK_PERI0_MSDC1		14
#define CLK_PERI0_MSDC2		15
#define CLK_PERI0_MSDC3		16
#define CLK_PERI0_MSDC4		17
#define CLK_PERI0_APHIF		18
#define CLK_PERI0_MDHIF		19
#define CLK_PERI0_NLI		20
#define CLK_PERI0_IRDA		21
#define CLK_PERI0_UART0		22
#define CLK_PERI0_UART1		23
#define CLK_PERI0_UART2		24
#define CLK_PERI0_UART3		25
#define CLK_PERI0_I2C0		26
#define CLK_PERI0_I2C1		27
#define CLK_PERI0_I2C2		28
#define CLK_PERI0_I2C3		29
#define CLK_PERI0_I2C4		30
#define CLK_PERI0_I2C5		31

#define CLK_PERI1_I2C6		32
#define CLK_PERI1_PWRAP		33
#define CLK_PERI1_AUXADC	34
#define CLK_PERI1_SPI1		35
#define CLK_PERI1_FHCTL		36

#define CLK_PERI_MUX_UART0	37
#define CLK_PERI_MUX_UART1	38
#define CLK_PERI_MUX_UART2	39
#define CLK_PERI_MUX_UART3	40


/* DISP */
#define CLK_DISP0_LARB2_SMI	0
#define CLK_DISP0_ROT_ENGINE	1
#define CLK_DISP0_ROT_SMI	2
#define CLK_DISP0_SCL		3
#define CLK_DISP0_OVL_ENGINE	4
#define CLK_DISP0_OVL_SMI	5
#define CLK_DISP0_COLOR		6
#define CLK_DISP0_2DSHP		7
#define CLK_DISP0_BLS		8
#define CLK_DISP0_WDMA0_ENGINE	9
#define CLK_DISP0_WDMA0_SMI	10
#define CLK_DISP0_WDMA1_ENGINE	11
#define CLK_DISP0_WDMA1_SMI	12
#define CLK_DISP0_RDMA0_ENGINE	13
#define CLK_DISP0_RDMA0_SMI	14
#define CLK_DISP0_RDMA0_OUTPUT	15
#define CLK_DISP0_RDMA1_ENGINE	16
#define CLK_DISP0_RDMA1_SMI	17
#define CLK_DISP0_RDMA1_OUTPUT	18
#define CLK_DISP0_GAMMA_ENGINE	19
#define CLK_DISP0_GAMMA_PIXEL	20
#define CLK_DISP0_CMDQ_ENGINE	21
#define CLK_DISP0_CMDQ_SMI	21
#define CLK_DISP0_G2D_ENGINE	22
#define CLK_DISP0_G2D_SMI	23

#define CLK_DISP1_DBI_ENGINE	24
#define CLK_DISP1_DBI_SMI	25
#define CLK_DISP1_DBI_OUTPUT	26
#define CLK_DISP1_DSI_ENGINE	27
#define CLK_DISP1_DSI_DIGITAL	28
#define CLK_DISP1_DSI_DIGITAL_LANE	29
#define CLK_DISP1_DPI0		30
#define CLK_DISP1_DPI1		31
#define CLK_DISP1_LCD		32
#define CLK_DISP1_SLCD		33


/* IMG */
#define CLK_IMAGE_LARB3_SMI	0
#define CLK_IMAGE_LARB4_SMI	1
#define CLK_IMAGE_COMMN_SMI	2
#define CLK_IMAGE_CAM_SMI	3
#define CLK_IMAGE_CAM_CAM	4
#define CLK_IMAGE_SEN_TG	5
#define CLK_IMAGE_SEN_CAM	6
#define CLK_IMAGE_JPGD_SMI	7
#define CLK_IMAGE_JPGD_JPG	8
#define CLK_IMAGE_JPGE_SMI	9
#define CLK_IMAGE_JPGE_JPG	10
#define CLK_IMAGE_FPC		11


/* MFG */
#define CLK_MFG_AXI		0
#define CLK_MFG_MEM		1
#define CLK_MFG_G3D		2
#define CLK_MFG_HYD		3


/* AUD */
#define CLK_AUDIO_AFE		0
#define CLK_AUDIO_I2S		1


/* VDEC */
#define CLK_VDEC0_VDE		0

#define CLK_VDEC1_SMI		1


/* VENC */
#define CLK_VENC_VEN		0
