// SPDX-License-Identifier: MIT OR GPL-2.0-only

#ifndef __TTRACE_TOKENS_H__
#define __TTRACE_TOKENS_H__

/* All defines should use decimal so to not confuse the post processing tool */

/* Trace groups */
#define PVRSRV_TRACE_GROUP_KICK		0
#define PVRSRV_TRACE_GROUP_TRANSFER	1
#define PVRSRV_TRACE_GROUP_QUEUE	2
#define PVRSRV_TRACE_GROUP_POWER	3
#define PVRSRV_TRACE_GROUP_MKSYNC	4
#define PVRSRV_TRACE_GROUP_MODOBJ	5

#define PVRSRV_TRACE_GROUP_PADDING	255

/* Trace classes */
#define PVRSRV_TRACE_CLASS_FUNCTION_ENTER	0
#define PVRSRV_TRACE_CLASS_FUNCTION_EXIT	1
#define PVRSRV_TRACE_CLASS_SYNC				2
#define PVRSRV_TRACE_CLASS_CCB				3
#define PVRSRV_TRACE_CLASS_CMD_START		4
#define PVRSRV_TRACE_CLASS_CMD_END			5
#define PVRSRV_TRACE_CLASS_CMD_COMP_START	6
#define PVRSRV_TRACE_CLASS_CMD_COMP_END		7
#define PVRSRV_TRACE_CLASS_FLAGS			8
#define PVRSRV_TRACE_CLASS_DEVVADDR			9
#define PVRSRV_TRACE_CLASS_FRAMENUM			10

#define PVRSRV_TRACE_CLASS_NONE				255

/* Operation about to happen on the sync object */
#define PVRSRV_SYNCOP_SAMPLE		0
#define PVRSRV_SYNCOP_COMPLETE		1
#define PVRSRV_SYNCOP_DUMP			2

/*
 * Trace tokens
 * ------------
 * These only need to unique within a group.
 */

/* Kick group tokens */
#define KICK_TOKEN_DOKICK			0
#define KICK_TOKEN_CCB_OFFSET		1
#define KICK_TOKEN_TA3D_SYNC		2
#define KICK_TOKEN_TA_SYNC			3
#define KICK_TOKEN_3D_SYNC			4
#define KICK_TOKEN_SRC_SYNC			5
#define KICK_TOKEN_DST_SYNC			6
#define KICK_TOKEN_FIRST_KICK		7
#define KICK_TOKEN_LAST_KICK		8
#define KICK_TOKEN_HWRTDATASET		9
#define KICK_TOKEN_HWRTDATA			10
#define KICK_TOKEN_FRAMENUM			11
#define KICK_TOKEN_RENDERCONTEXT	12

/* Transfer Queue group tokens */
#define TRANSFER_TOKEN_SUBMIT		0
#define TRANSFER_TOKEN_TA_SYNC		1
#define TRANSFER_TOKEN_3D_SYNC		2
#define TRANSFER_TOKEN_SRC_SYNC		3
#define TRANSFER_TOKEN_DST_SYNC		4
#define TRANSFER_TOKEN_CCB_OFFSET	5

/* Queue group tokens */
#define QUEUE_TOKEN_GET_SPACE			0
#define QUEUE_TOKEN_INSERTKM			1
#define QUEUE_TOKEN_SUBMITKM			2
#define QUEUE_TOKEN_PROCESS_COMMAND		3
#define QUEUE_TOKEN_PROCESS_QUEUES		4
#define QUEUE_TOKEN_COMMAND_COMPLETE	5
#define QUEUE_TOKEN_UPDATE_DST			6
#define QUEUE_TOKEN_UPDATE_SRC			7
#define QUEUE_TOKEN_SRC_SYNC			8
#define QUEUE_TOKEN_DST_SYNC			9
#define QUEUE_TOKEN_COMMAND_TYPE		10

/* uKernel Sync tokens */
#define MKSYNC_TOKEN_KERNEL_CCB_OFFSET	0
#define MKSYNC_TOKEN_CORE_CLK			1
#define MKSYNC_TOKEN_UKERNEL_CLK		2

/* ModObj tokens */
#define MODOBJ_TOKEN_MODIFY_PENDING		0
#define MODOBJ_TOKEN_COMPLETE_PENDING	1
#define MODOBJ_TOKEN_READ_SYNC			2
#define MODOBJ_TOKEN_WRITE_SYNC			3
#define MODOBJ_TOKEN_READ_WRITE_SYNC	4
#define MODOBJ_TOKEN_SYNC_UPDATE		5
#define MODOBJ_TOKEN_READ2_SYNC			6

#endif /* __TTRACE_TOKENS_H__ */
