obj-$(CONFIG_MTK_MT6628_STP) += mtk-stp.o
obj-$(CONFIG_MTK_MT6628_FM) += mtk-fm.o
obj-$(CONFIG_MTK_MT6628_WLAN) += mtk-wlan.o mt6628-wlan-runtime.o mt6628-wlan-cmd.o mt6628-wlan-cfg80211.o mt6628-wlan-control.o mt6628-wlan-connect.o
