# SPDX-License-Identifier: GPL-2.0-only
prismrv-y := \
	prismrv_drv.o \
	prismrv_device.o \
	prismrv_errata.o \
	prismrv_fw.o \
	prismrv_init.o \
	prismrv_mmu.o \
	prismrv_gem.o \
	prismrv_submit.o \
	prismrv_irq.o \
	prismrv_devfreq.o

obj-$(CONFIG_DRM_PRISMRV) += prismrv.o
